services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    restart: always

  node:
    # stuff

  sqlite:
    # stuff
