import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pixel = localFont({
  src: "../public/PixelFont.ttf",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixel.className} antialiased text-lg`}
      >
        {children}
      </body>
    </html>
  );
}
