services:
  app:
    build:
      context: ../app
      dockerfile: ../infra/app.Dockerfile
    image: app
    container_name: app
    ports:
      - "8080:80"
    depends_on:
      - accounts_service
    restart: always

  accounts_service:
    build:
      context: ..
      dockerfile: infra/accounts_service.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    volumes:
      - ../core/accounts_service:/app
    restart: always
