services:
  # app:
  #   build:
  #     context: ../app
  #     dockerfile: ../infra/app.Dockerfile
  #   image: app
  #   container_name: app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GAME_SERVICE_URL=http://game_service:3002/ws
  
  #   depends_on:
  #     - accounts_service
  #     # - game_service
  #   restart: always

  accounts_service:
    build:
      context: ..
      dockerfile: infra/accounts_service.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    volumes:
      - ../core/accounts_service:/app
    restart: always

  # game_service:
  #   build:
  #     context: ..
  #     dockerfile: infra/game_service.Dockerfile
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     - DEBUG=False
  #   restart: always

  ngrok_accounts_service:
    build:
      context: ..
      dockerfile: infra/ngrok.Dockerfile
    image: ngrok
    container_name: ngrok_accounts_service
    environment:
      - NGROK_AUTHTOKEN=31ZN8je7Gz1VwB96jp6ljpLfATm_6zfJHDU1miPTNH4AifVnZ
    ports:
      - "4041:4040"
    volumes:
      - ../infra/accounts_service.yml:/app/ngrok.yml:ro
    depends_on:
      - accounts_service
    restart: always